const flappyBirdX = 'x';
const flappyBirdY = 'y';
const flappyBirdRotationDeg = 'rotation_deg';
const flappyBirdColor = 'color';
const flappyBirdFlightStage = 'flight_stage';
const flappyBirdIsJumping= 'is_jumping';
const flappyBirdDir = 'movement_direction';
const heightToJump = 'dist_since_last_jump';
const flappyBirdIsFalling = 'flappy_bird_is_falling';